// Generates supabase/seed.sql from src/config/election.ts (the single place
// for editable election content) plus a deterministic list of fictional voters.
//
//   npm run seed:generate

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { CANDIDATES, ELECTION } from '../src/config/election.ts'

const VOTER_COUNT = 400
// Three angkatan (entry years). NIS format: 99 + 2-digit year + 3-digit number.
// The "99" prefix marks the numbers as demo data.
const ANGKATAN = [21, 22, 23]

const MALE_FIRST = [
  'Ahmad', 'Muhammad', 'Rizky', 'Fajar', 'Dimas', 'Bagas', 'Arya', 'Hafidz', 'Naufal', 'Farhan',
  'Ilham', 'Reza', 'Galih', 'Yusuf', 'Zaki', 'Hanif', 'Rafi', 'Daffa', 'Akbar', 'Fikri',
  'Iqbal', 'Bayu', 'Aditya', 'Rangga', 'Wildan', 'Faiz', 'Abdullah', 'Haikal', 'Azka', 'Alif',
]
const FEMALE_FIRST = [
  'Aisyah', 'Nabila', 'Zahra', 'Alya', 'Hana', 'Fatimah', 'Nayla', 'Aulia', 'Kirana', 'Rahma',
  'Dinda', 'Laila', 'Khansa', 'Najwa', 'Amira', 'Tiara', 'Anisa', 'Farah', 'Latifa', 'Zakiyah',
  'Maryam', 'Rania', 'Keysha', 'Adinda', 'Salma', 'Hilya', 'Qonita', 'Shafa', 'Nurul', 'Intan',
]
const MALE_MIDDLE = ['Nur', 'Fadhil', 'Rizqi', 'Dwi', 'Adi', 'Abdul', 'Hasan', 'Fathur', 'Bima', 'Ikhsan']
const FEMALE_MIDDLE = ['Putri', 'Nur', 'Ayu', 'Dewi', 'Sri', 'Zahira', 'Aulia', 'Kamila', 'Rizka', 'Tsania']
const MALE_LAST = [
  'Pratama', 'Saputra', 'Ramadhan', 'Hidayat', 'Nugroho', 'Wibowo', 'Maulana', 'Firmansyah',
  'Setiawan', 'Kurniawan', 'Santoso', 'Fauzi', 'Syahputra', 'Rahman', 'Permana', 'Anwar',
  'Wijaya', 'Hamzah', 'Prasetyo', 'Alfarizi',
]
const FEMALE_LAST = [
  'Rahmawati', 'Lestari', 'Maharani', 'Safitri', 'Kusuma', 'Wulandari', 'Nuraini', 'Fitriani',
  'Handayani', 'Amalia', 'Anggraini', 'Purnama', 'Ramadhani', 'Azzahra', 'Salsabila', 'Khoirunnisa',
  'Mufidah', 'Hasanah', 'Oktaviani', 'Puspita',
]

// Small seeded PRNG so the generated file is stable between runs.
function mulberry32(seed: number) {
  return () => {
    seed |= 0
    seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
const random = mulberry32(2023)
const pick = <T,>(list: T[]) => list[Math.floor(random() * list.length)]

function voterName() {
  const male = random() < 0.5
  const first = pick(male ? MALE_FIRST : FEMALE_FIRST)
  const last = pick(male ? MALE_LAST : FEMALE_LAST)
  if (random() < 0.45) return `${first} ${pick(male ? MALE_MIDDLE : FEMALE_MIDDLE)} ${last}`
  return `${first} ${last}`
}

const sql = (value: string) => `'${value.replaceAll("'", "''")}'`

const voters: { nis: string; nama: string }[] = []
for (let i = 0; i < VOTER_COUNT; i++) {
  const year = ANGKATAN[i % ANGKATAN.length]
  const number = Math.floor(i / ANGKATAN.length) + 1
  voters.push({ nis: `99${year}${String(number).padStart(3, '0')}`, nama: voterName() })
}
voters.sort((a, b) => a.nis.localeCompare(b.nis))

const candidateRows = CANDIDATES.map(
  (c) =>
    `  (${c.nomor_urut}, ${sql(c.ketua_nama)}, ${sql(c.wakil_nama)},\n` +
    `   ${sql(c.visi)},\n` +
    `   array[\n${c.misi.map((m) => `     ${sql(m)}`).join(',\n')}\n   ],\n` +
    `   ${sql(c.accent_color)})`,
)

const boothRows = Array.from(
  { length: ELECTION.boothCount },
  (_, i) => `  (${i + 1}, ${sql(`Bilik ${i + 1}`)})`,
)

const voterRows = voters.map((v) => `  (${sql(v.nis)}, ${sql(v.nama)})`)

const output = `-- =============================================================================
-- PEMILU — seed data
-- GENERATED by scripts/generate-seed.ts from src/config/election.ts.
-- Do not edit by hand: change the config and run \`npm run seed:generate\`.
--
-- Running this again wipes all election data (votes, voters, candidates) and
-- starts fresh. Staff accounts and roles are left alone.
-- =============================================================================

begin;

delete from public.booth_assignments;
delete from public.public_results;
delete from public.tally;
delete from public.candidates;
delete from public.voters;
delete from public.booths;
delete from public.election;
delete from public.public_turnout;

insert into public.election (id, name, status)
values (1, ${sql(ELECTION.name)}, 'belum_dibuka');

insert into public.candidates (nomor_urut, ketua_nama, wakil_nama, visi, misi, accent_color)
values
${candidateRows.join(',\n')};

insert into public.tally (candidate_id)
select id from public.candidates;

insert into public.booths (id, label)
values
${boothRows.join(',\n')};

-- ${VOTER_COUNT} fictional voters (siswa).
insert into public.voters (nis, nama)
values
${voterRows.join(',\n')};

insert into public.public_turnout (id, total_dpt, voted_count, status)
select 1, count(*), 0, 'belum_dibuka' from public.voters;

commit;
`

const target = fileURLToPath(new URL('../supabase/seed.sql', import.meta.url))
writeFileSync(target, output)
console.log(`Wrote ${target} (${CANDIDATES.length} candidates, ${VOTER_COUNT} voters)`)
